MIDlet-Vendor:Jonathan A
MIDlet-Version:1.0.0
Manifest-Version:1.0
Created-By:1.4.2_09 (Sun Microsystems Inc.)
MIDlet-Icon:/icon.png
MicroEdition-Configuration:CLDC-1.0
MIDlet-Name:Gangstar Crime City
MIDlet-Description:Modificado Por Jonathan A
MIDlet-1:Gangstar Crime City, /icon.png, GloftGANG
MicroEdition-Profile:MIDP-2.0
